Repository puppetlabs/puppetlabs-wsus_client, pull requests merged in 2023-04, with the labels that each got.

#201 pdksync - (CONT-844) - Update .sync.yml
  .sync.yml
Labels: maintenance

#202 (CONT-860) Update registry dependency
  metadata.json
Labels: bugfix

#204 (CONT-804) Add Support for Puppet 8 / Drop Support for Puppet 6
  .fixtures.yml
  .github/workflows/auto_release.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .rubocop.yml
  .rubocop_todo.yml
  .sync.yml
  Gemfile
  Rakefile
  lib/puppet/parser/functions/parse_auto_update_option.rb
  lib/puppet/parser/functions/parse_scheduled_install_day.rb
  lib/puppet/parser/functions/validate_in_range.rb
  manifests/init.pp
  manifests/setting.pp
  metadata.json
  spec/acceptance/wsus_client_spec.rb
  spec/classes/init_spec.rb
  spec/spec_helper.rb
Labels: backwards-incompatible
